build:
  Version: 1.0
accounts:
  message: "Welcome to EazyBank accounts related prod APIs"
  contactDetails:
    name: "Abebe - implementer"
    email: "abebe@eazybank.com"
  onCallSupport:
    - "(777) 555-1234"
    - "(777) 523-1345"

